
addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  # - INSTANCE=smoke-package-stable-centos-6 # terribly slow; takes more than 45 minutes
  - INSTANCE=smoke-package-stable-centos-7
  - INSTANCE=smoke-package-stable-debian-9
  - INSTANCE=smoke-package-stable-debian-10
  - INSTANCE=smoke-package-stable-ubuntu-1604
  - INSTANCE=smoke-package-stable-ubuntu-1804
  # - INSTANCE=smoke-war-stable-centos-6 # terribly slow; takes more than 45 minutes
  - INSTANCE=smoke-war-stable-centos-7
  - INSTANCE=smoke-war-stable-debian-9
  - INSTANCE=smoke-war-stable-debian-10
  - INSTANCE=smoke-war-stable-ubuntu-1604
  - INSTANCE=smoke-war-stable-ubuntu-1804

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
